<?php
require_once dirname(__FILE__).'/../../../controllers/MouseController.php';
?>
<div class="span-20">
<div class="span-10"><h2><?=$this->escape($this->title)?></h2></div>
<div class="span-10 last" style="text-align: right;">
Last modified <?=$this->escape(mdb_Globals::formatDateTime($this->lastmodified))?> by <?=$this->escape($this->lastmodifiedby)?>
</div>
</div>
<?=$this->form?>
<a href="<?=$this->url ( array ('controller' => 'litter', 'action' => 'view', 'id' => $this->id ), null, true )?>">Back to litter details</a>