<h2><?=$this->escape($this->title)?></h2>
<?=$this->form?>
<hr />
<?php if (count($this->parents) == 0) : ?>
<h3 class="notice">Parents unknown.</h3>
<?php else : ?>
<h3>Parents</h3>
<table class="expand sortable">
<tr>
	<th>Mouse</th>
	<th>Sex</th>
	<th>Alive</th>
	<th>Strain</th>
	<th>Min/MaxP</th>
	<th>Genotype</th>
	<th>DOB</th>
	<th>Wks</th>
	<th>Gen</th>
</tr>
<?php foreach ( $this->parents as $parent ) : ?>
<tr>
	<td><a href="<?=$this->url ( array ('controller' => 'mouse', 'action' => 'view', 'id' => $parent['id'] ), null, true )?>"><?=$this->escape ( $parent['assigned_id'] )?></a></td>
	<td><?=$this->escape ( $parent['sex'] )?></td>
	<td><?=$this->escape ( $parent['is_alive'] ? 'Y' : 'N' )?></td>
	<td><a href="<?=$this->url ( array ('controller' => 'strain', 'action' => 'view', 'id' => $parent['strain_id'] ), null, true )?>"><?=$this->escape ( $parent['strain_name'] )?></a></td>
	<td><?=$this->escape ( $parent['promoter'] )?></td>
	<td><?=$this->escape ( $parent['genotype'] )?></td>
	<td><?=$this->escape ( mdb_Globals::formatDateTime($parent['born_on']) )?></td>
	<td><?=$this->escape ( round($parent['born_days'] / 7, 1) )?></td>
	<td><?=$this->escape ( $parent['generation'] )?></td>
</tr>
<?php endforeach; ?>
</table>
<?php endif; ?>
