<h2><?=$this->escape($this->title)?></h2>
<?=$this->form?>
<?php if ($this->canDelete) { ?>
<?php $this->dojo()->enable()->requireModule('dijit.Dialog'); ?>
<div id="deleteDialog" dojoType="dijit.Dialog" title="Confirm Delete" style="display:none;">
<div style="padding:1em; max-width:500px;">
<p>Are you sure that you want to delete '<?=$this->escape($this->title)?>'?</p>
<form action="<?=$this->url(array('action'=>'delete'))?>" method="post">
If this user created comments or tags:<br /><br />
<?=$this->radioButton('delete_policy', Users::COMMENT_RESTRICT, array(), array(),
	array(Users::COMMENT_RESTRICT => 'Do not delete this user',
		Users::COMMENT_DELETE => 'Delete this user and user\'s tags and comments',
		Users::COMMENT_ANON => 'Delete this user and set user\'s tags and comments to anonymous'))?>
<br /><br />
<?=$this->submitButton('deleteSubmit', 'Delete')?>
<?=$this->button('deleteCancel', 'Cancel', array('onclick' => "dijit.byId('deleteDialog').hide()"))?>
</form>
</div>
</div>
<?php } ?>