<?php Zend_Dojo::enableView($this);?>
<?php

function makeCageLink(Zend_View_Abstract $view, $cage_id, $cage_assigned_id, $cagetype) {
	if ($cage_id) {
		switch ($cagetype) {
			case Cages::BREEDING :
				$href = $view->url ( array ('controller' => 'breeding-cage', 'action' => 'view', 'id' => $cage_id ), null, true );
				break;
			case Cages::WEANING :
				$href = $view->url ( array ('controller' => 'weaning-cage', 'action' => 'view', 'id' => $cage_id ), null, true );
				break;
			case Cages::HOLDING :
				$href = $view->url ( array ('controller' => 'holding-cage', 'action' => 'view', 'id' => $cage_id ), null, true );
				break;
			default:
				$href='';
				mdb_Messages::add ( '\''.$cagetype . '\' is unknown cage type', 'error' );
				break;
		}
		return '<a href="' . $href . '" title = "' . $view->escape($cagetype) . '">' . $view->escape($cage_assigned_id) . '</a>';
	} else {
		return '';
	}
}
?>
<div class="span-20 last">
<div class="span-10"><h2><?=$this->escape($this->title)?></h2></div>
<div class="span-10 last" style="text-align: right;">
Last modified <?=$this->escape(mdb_Globals::formatDateTime($this->lastmodified))?> by <?=$this->escape($this->lastmodifiedby)?>
</div>
</div>
<?=$this->form?>
<script>
document.getElementById("chimera_score_div").innerHTML = "<strong>Chimera Score: "+(parseInt("0"+document.getElementById("chimera_perc_esc").value,10) + parseInt("0"+document.getElementById("chimera_perc_escblast").value,10)/2)+"</strong>";
</script>
<hr />
<?php if ($this->is_alive && $this->canSacrifice) : ?>
<form id="mouse-sac" action="<?=$this->url ( array ('controller' => 'mouse', 'action' => 'sacrifice'), null, true )?>" method="post" style="display:inline;">
<input type="hidden" name="id" value="<?=$this->mouse_id?>" id="sac_mouse_id">
<?=$this->submitButton('sacrifice', 'Sacrifice')?>
</form>&nbsp;&nbsp;
<?php elseif (! $this->is_alive && $this->canRevive) : ?>
<form id="mouse-sac" action="<?=$this->url ( array ('controller' => 'mouse', 'action' => 'revive'), null, true )?>" method="post" style="display:inline;">
<input type="hidden" name="id" value="<?=$this->mouse_id?>" id="sac_mouse_id">
<?=$this->submitButton('revive', 'Revive')?>
</form>&nbsp;&nbsp;
<?php endif; ?>
<?php if ($this->canTransfer) : ?>
<form id="mouse-xfer" action="<?=$this->url ( array ('controller' => 'mouse', 'action' => 'transfer'), null, true )?>" method="post" style="display:inline;">
<input type="hidden" name="xfer_mouse_id" value="<?=$this->mouse_id?>">
<input type="hidden" name="xfer_redirect" value="<?='/mouse/view/id/'.$this->mouse_id?>">
Move to cage
<?php echo $this->filteringSelect(
    'xfer_cage_id',
    null,
    array(
		'autocomplete' => 'false',
    	'hasDownArrow' => 'true',
		'store'        => 'xfer_cage_store',
		'searchAttr'   => 'item',
		'searchDelay'  => 200,
		'storeType'    => 'dojox.data.QueryReadStore',
		'storeParams'  => array('url' => $this->url ( array ('controller' => 'cage', 'action' => 'list', 'format' => 'json', 'type' => 'breeding|weanback|holding', 'mouse' => $this->mouse_id, 'exclude' => $this->current_cage_id ), null, true )),
    	'pageSize'     => 200,
    ) );
?>
<?=$this->submitButton('transfer', 'Transfer')?>
</form>&nbsp;&nbsp;
<?php endif; ?>
<?php if ($this->canDelete) :?>
<?php $this->dojo()->enable()->requireModule('dijit.Dialog'); ?>
<div id="deleteDialog" dojoType="dijit.Dialog" title="Confirm Delete" style="display:none;">
<div style="padding:1em; max-width:500px;">
Are you sure you want to delete &ldquo;<?=$this->escape($this->title)?>&rdquo;?
<br /><br />
<?=$this->button('deleteSubmit', 'Delete', array('onclick' => 'window.location = \''.$this->deleteURL.'\''))?>
<?=$this->button('deleteCancel', 'Cancel', array('onclick' => "dijit.byId('deleteDialog').hide()"))?>
</div>
</div>
<?php endif; ?>
<hr />
<?php if ($this->litter_id) : ?>
<h3>From litter <a href="<?=$this->url ( array ('controller' => 'litter', 'action' => 'view', 'id' => $this->litter_id), null, true )?>"><?=$this->escape($this->assigned_litter_id)?></a></h3>
<?php endif; ?>
<?php if (count($this->parents) == 0) : ?>
<h3 class="notice">Parents unknown.</h3>
<?php else : ?>
<h3>Parents</h3>
<table class="expand sortable">
	<tr>
		<th>Mouse</th>
		<th>Sex</th>
		<th>Alive</th>
		<th>Strain</th>
		<th>Min/MaxP</th>
		<th>Genotype</th>
		<th>DOB</th>
		<th>Wks</th>
		<th>Gen</th>
	</tr>
<?php foreach ( $this->parents as $parent ) : ?>
<tr>
		<td><a href="<?=$this->url ( array ('controller' => 'mouse', 'action' => 'view', 'id' => $parent['id'] ), null, true )?>"><?=$this->escape ( $parent['assigned_id'] )?></a></td>
		<td><?=$this->escape ( $parent['sex'] )?></td>
		<td><?=$this->escape ( $parent['is_alive'] ? 'Y' : 'N' )?></td>
		<td><a href="<?=$this->url ( array ('controller' => 'strain', 'action' => 'view', 'id' => $parent['strain_id'] ), null, true )?>"><?=$this->escape ( $parent['strain_name'] )?></a></td>
		<td><?=$this->escape ( $parent['promoter'] )?></td>
		<td><?=$this->escape ( $parent['genotype'] )?></td>
		<td><?=$this->escape ( mdb_Globals::formatDateTime($parent['born_on']) )?></td>
		<td><?=$this->escape ( round($parent['born_days'] / 7, 1) )?></td>
		<td><?=$this->escape ( $parent['generation'] )?></td>
	</tr>
<?php endforeach; ?>
</table>
<?php endif; ?>
<hr />
<?php if ($this->current_cage_id) :?>
<div>
<h3 style="display:inline;">Current cage <?=makeCageLink($this, $this->current_cage_id, $this->current_cage_assigned_id, $this->current_cagetype)?>
<?php if ($this->current_cagetype == 'breeding') :?></h3>
<button dojoType="dijit.form.Button" style="margin-left:2em;" onClick="window.location = '<?=$this->url ( array ('controller' => 'mouse', 'action' => 'transfer', 'xfer_mouse_id' => $this->mouse_id, 'xfer_notes' => 'move to limbo', 'xfer_redirect' => 'themouse' ), null, true )?>'">
Remove from cage</button>
</div>
<?php endif; ?>
<?php endif; ?>
<?php if ( count($this->litters) > 0 ) :?>
<hr />
<h3>Litters <?= $this->form->sex->getValue() == 'F' ? 'mothered' : 'sired' ?></h3>
<table class="expand sortable">
	<tr>
		<th>Litter</th>
		<th>Born On</th>
		<th>Weaned On</th>
		<th>Alive Pups</th>
		<th>Strain</th>
	</tr>
<?php foreach ($this->litters as $litter) :?>
	<tr>
		<td><a href="<?=$this->url ( array ('controller' => 'litter', 'action' => 'view', 'id' => $litter['id'] ), null, true )?>"><?=$this->escape ( $litter['assigned_id'] )?></a></td>
		<td><?=$this->escape ( mdb_Globals::formatDateTime($litter['born_on']) )?></td>
		<td><?=$this->escape ( mdb_Globals::formatDateTime($litter['weaned_on']) )?></td>
		<td><?=$this->escape ( $litter['alive_pups'] )?></td>
		<td><?=$this->escape ( $litter['strain_name'] )?></td>
	</tr>
<?php endforeach;?>
</table>
<?php endif; ?>
<?php if ( count($this->transfers) ) :?>
<hr />
<h3>Cage transfers</h3>
<table class="expand sortable">
	<tr>
		<th>On</th>
		<th>From</th>
		<th>To</th>
		<th>Reason</th>
		<th>User</th>
		<th class="sorttable_nosort noprint"></th>
	</tr>
<?php foreach ($this->transfers as $transfer) :?>
	<tr>
		<td><?=$this->escape ( mdb_Globals::formatDateTime($transfer['transferred_on']) )?></td>
		<td><?=makeCageLink ( $this, $transfer['from_cage_id'], $transfer['from_cage_assigned_id'], $transfer['from_cagetype'] )?></td>
		<td><?=makeCageLink ( $this, $transfer['to_cage_id'], $transfer['to_cage_assigned_id'], $transfer['to_cagetype'] )?></td>
		<td><?=$this->escape ( $transfer['notes'] )?></td>
		<td><?=$this->escape ( $transfer['username'] )?></td>
<td style="text-align:right;"><form method="post" action="<?=$this->url ( array ('controller' => 'transfer', 'action' => 'view', 'id' =>  $transfer['id'] ), null, true ) ?>"
><input type="hidden" name="redirect" value="<?= '/mouse/view/id/' . $this->cage_id ?>" /><input type="hidden" name="edit" value="true"
 /><?=$this->submitButton('submit_xfer_'.$transfer['id'], 'Edit', array(), array('style' => 'margin-top: -4px; margin-bottom: -2px')) ?></form></td>
	</tr>
<?php endforeach;?>
</table>
<?php endif; ?>
<?php
echo $this->contentPane('tag_pane', null,
    array('href' => $this->url( array('controller' => 'tag', 'action' => 'view', 'table' => Tags::MOUSE, 'item' => $this->mouse_id,  'format' => 'html' ), null, true ),
    	'parseOnLoad' => 'true',
    	'loadingMessage' => '',
    	'preload' => 'true'),
    array('style' => 'padding:2px;')
        )
?>
<?php
echo $this->contentPane('comment_pane', null,
    array('href' => $this->url( array('controller' => 'comment', 'action' => 'view', 'table' => Comments::MOUSE, 'item' => $this->mouse_id,  'format' => 'html' ), null, true ),
    	'parseOnLoad' => 'true',
    	'loadingMessage' => '',
    	'preload' => 'true'),
    array('style' => 'padding:2px;')
    )
?>
