<?php Zend_Dojo::enableView($this);?>
<?php
//Zend_Dojo_View_Helper_Dojo::setUseDeclarative(true);

function makeCageLink(Zend_View_Abstract $view, $cage_id, $cage_assigned_id, $cagetype, $this_cage_id) {
	if ($cage_id) {
		if ($cage_id == $this_cage_id) {
			return '<em>here</em>';
		} else {
			switch ($cagetype) {
				case Cages::BREEDING :
					$href = $view->url ( array ('controller' => 'breeding-cage', 'action' => 'view', 'id' => $cage_id ), null, true );
					break;
				case Cages::WEANING :
					$href = $view->url ( array ('controller' => 'weaning-cage', 'action' => 'view', 'id' => $cage_id ), null, true );
					break;
				case Cages::HOLDING :
					$href = $view->url ( array ('controller' => 'holding-cage', 'action' => 'view', 'id' => $cage_id ), null, true );
					break;
				default:
					$href='';
					mdb_Messages::add ( '\''.$cagetype . '\' is unknown cage type', 'error' );
					break;
			}
			return '<a href="' . $href . '" title = "' . $view->escape($cagetype) . '">' . $view->escape($cage_assigned_id) . '</a>';
		}
	} else {
		return '';
	}
}
?>
<div class="span-20 last">
<div class="span-10"><h2><?=$this->escape($this->title)?></h2></div>
<div class="span-10 last" style="text-align: right;">
Last modified <?=$this->escape(mdb_Globals::formatDateTime($this->lastmodified))?> by <?=$this->escape($this->lastmodifiedby)?>
<?php
$related_snippet = array();
foreach ($this->related_cages as $related_cage) {
	if ($related_cage['id'] == $this->cage_id) {
		$related_snippet[] = '<span style="color:gray">'.$related_cage['assigned_id'].'</span>';
	} else {
		$related_snippet[] = '<a href="'.$this->url ( array ('controller' => 'breeding-cage', 'action' => 'view', 'id' => $related_cage['id'] ), null, true ).'">'.$related_cage['assigned_id'].'</a>';
	}
}
if (count($related_snippet)) {
	echo '<br /><span class="small">'.implode(' ', $related_snippet).'</span>';
}
?>
</div>
</div>
<?php if ($this->old_cage_notify != '') : ?>
<div class="span-20 last notice"><?=$this->old_cage_notify?></div>
<?php endif; ?>
<?=$this->form?>
<?php if ($this->canDelete) : ?>
<?php $this->dojo()->enable()->requireModule('dijit.Dialog'); ?>
<div id="deleteDialog" dojoType="dijit.Dialog" title="Confirm Delete" style="display:none;">
<div style="padding:1em; max-width:500px;">
Are you sure you want to delete &ldquo;<?=$this->escape($this->title)?>&rdquo;?
<br /><br />
<?=$this->button('deleteSubmit', 'Delete', array('onclick' => 'window.location = \''.$this->deleteURL.'\''))?>
<?=$this->button('deleteCancel', 'Cancel', array('onclick' => "dijit.byId('deleteDialog').hide()"))?>
</div>
</div>
<?php endif; ?>
<hr />
<?php if (count($this->breeders) == 0) : ?>
<h3>There are no breeders present in this cage</h3>
<?php else : ?>
<h3>Breeders present in this cage</h3>
<table class="expand sortable">
	<tr>
		<th>Mouse</th>
		<th>Alive</th>
		<th>Sex</th>
		<th>Strain</th>
		<th>Min/MaxP</th>
		<th>Geno.</th>
		<th>DOB</th>
		<th>Wks</th>
		<th>Gen</th>
		<th class="sorttable_nosort noprint"></th>
	</tr>
<?php foreach ( $this->breeders as $breeder ) : ?>
<tr<?= ($breeder['is_alive'] ? '' : ' style="color:gray;"') ?>>
		<td><a href="<?=$this->url ( array ('controller' => 'mouse', 'action' => 'view', 'id' => $breeder['id'] ), null, true )?>"><?=$this->escape ( $breeder['assigned_id'] )?></a></td>
		<td><?=$this->escape ( $breeder['is_alive'] ? 'Y' : 'N' )?></td>
		<td><?=$this->escape ( $breeder['sex'] )?></td>
		<td><a href="<?=$this->url ( array ('controller' => 'strain', 'action' => 'view', 'id' => $breeder['strain_id'] ), null, true )?>"><?=$this->escape ( $breeder['strain_name'] )?></a></td>
		<td><?=$this->escape ( $breeder['promoter'] )?></td>
		<td><?=$this->escape ( $breeder['genotype'] )?></td>
		<td><?=$this->escape ( mdb_Globals::formatDateTime($breeder['born_on']) )?></td>
		<td><?=$this->escape ( round($breeder['born_days'] / 7, 1) )?></td>
		<td><?=$this->escape ( $breeder['generation'] )?></td>
<td class="noprint" style="text-align:right; color:black;"
><?php If ($breeder['is_alive'] && $this->canSacrifice) : ?><form
method="post" action="<?=$this->url ( array ('controller' => 'mouse', 'action' => 'sacrifice', 'id' =>  $breeder['id'] ), null, true ) ?>"><input
type="hidden" name="redirect" value="<?= '/breeding-cage/view/id/' . $this->cage_id ?>" /><input
type="hidden" name="id" value="<?=$breeder['id']?>"
/><?=$this->submitButton('submit_sacr_'.$breeder['id'], 'Sacr.', array(), array('style' => 'margin-top: -4px; margin-bottom: -2px', 'title' => 'Sacrifice mouse '.$breeder['assigned_id']))
?></form><?php elseif (! $breeder['is_alive'] && $this->canRevive) : ?><form
method="post" action="<?=$this->url ( array ('controller' => 'mouse', 'action' => 'revive', 'id' =>  $breeder['id'] ), null, true ) ?>"><input
type="hidden" name="redirect" value="<?= '/breeding-cage/view/id/' . $this->cage_id ?>" /><input
type="hidden" name="id" value="<?=$breeder['id']?>" /><?=$this->submitButton('submit_sacr_'.$breeder['id'], 'Revive',
array(), array('style' => 'margin-top: -4px; margin-bottom: -2px', 'title' => 'Revive mouse '.$breeder['assigned_id'])) ?></form><?php endif; ?></td>
	</tr>
<?php endforeach; ?>
</table>
<?php endif; ?>
<?php if ($this->assigned_stud_id) : ?>
<div>Assigned stud:
<a href="<?=$this->url ( array ('controller' => 'mouse', 'action' => 'view', 'id' => $this->assigned_stud_id ), null, true )?>"><?=$this->assigned_stud_cmmt_id?>
</a>
<?php $this->dojo()->addDijit('unassign_stud', array('dojoType' => 'dijit.form.Button'))?>
<button id="unassign_stud" style="margin-left:2em;" onclick="window.location = '<?=$this->url ( array ('controller' => 'breeding-cage', 'action' => 'unassignstud', 'id' => $this->cage_id ), null, true )?>'">
Unassign this stud</button>
</div>
<?php endif; ?>
<?php if ($this->canTransfer) : ?>
<form id="mouse-xfer" action="<?=$this->url ( array ('controller' => 'mouse', 'action' => 'transfer'), null, true )?>" method="post">
<input type="hidden" name="xfer_cage_id" value="<?=$this->cage_id?>">
<input type="hidden" name="xfer_redirect" value="<?='/breeding-cage/view/id/'.$this->cage_id?>">
Move mouse&nbsp;
<?php echo $this->filteringSelect(
    'xfer_mouse_id',
    null,
    array(
		'autocomplete' => 'false',
    	'hasDownArrow' => 'true',
		'store'        => 'xferMouseStore',
		'searchAttr'   => 'item',
		'searchDelay'  => 200,
		'storeType'    => 'dojox.data.QueryReadStore',
		'storeParams'  => array('url' => $this->url ( array ('controller' => 'mouse', 'action' => 'list', 'format' => 'json' ), null, true )),
    	'pageSize'     => 200,
    ),
    array('style' => 'display:inline-block;')
    );
?>
&nbsp;to this cage&nbsp;
<?=$this->submitButton('transfer', 'Transfer')?>
</form>
<?php endif; ?>
<hr />
<?php if ($this->canCreateLitter) :?>
<h4>
<a href="<?=$this->url ( array ('controller' => 'litter', 'action' => 'new', 'cage' => $this->cage_id	 ), null, true )?>">Create new litter&hellip;</a>
</h4>
<?php endif; ?>
<?php if (count($this->litters) == 0) : ?>
<h3>There were no litters born in this cage</h3>
<?php else : ?>
<h3>Litters born in this cage</h3>
<table class="expand sortable">
	<tr>
		<th>Litter</th>
		<th>DOB</th>
		<th>Born</th>
		<th>Alive</th>
		<th>Total Females</th>
		<th>Total Males</th>
		<th>DOW</th>
	</tr>
<?php foreach ( $this->litters as $litter ) : ?>
<tr>
		<td><a href="<?=$this->url ( array ('controller' => 'litter', 'action' => 'view', 'id' => $litter['id'] ), null, true )?>"><?=$this->escape ( $litter['assigned_id'] )?></a></td>
		<td><?=$this->escape ( mdb_Globals::formatDateTime($litter['born_on']) )?></td>
		<td><?=$this->escape ( $litter['total_pups'] )?></td>
		<td><?=$this->escape ( $litter['alive_pups'] )?></td>
		<td><?=$litter['weaned_on'] ? $this->escape ( $litter['weaned_female_count'] + $litter['holding_female_count'] + $litter['sacrificed_female_count'] ) : ''?></td>
		<td><?=$litter['weaned_on'] ? $this->escape ( $litter['weaned_male_count'] + $litter['holding_male_count'] + $litter['sacrificed_male_count'] ) : ''?></td>
		<td><?=$this->escape ( mdb_Globals::formatDateTime($litter['weaned_on']) )?></td>
	</tr>
<?php endforeach; ?>
</table>
<?php endif; ?>
<?php if ( count($this->transfers) ) :?>
<hr />
<h3>Cage transfers</h3>
<table class="expand sortable">
	<tr>
		<th>Mouse</th>
		<th>On</th>
		<th>From</th>
		<th>To</th>
		<th>Reason</th>
		<th>User</th>
		<th class="sorttable_nosort noprint"></th>
	</tr>
<?php foreach ($this->transfers as $transfer) :?>
	<tr>
		<td><a href="<?=$this->url ( array ('controller' => 'mouse', 'action' => 'view', 'id' => $transfer['mouse_id'] ), null, true )?>"><?=$this->escape ( $transfer['mouse_assigned_id'] )?></a></td>
		<td><?=$this->escape ( mdb_Globals::formatDateTime($transfer['transferred_on']) )?></td>
		<td><?=makeCageLink ( $this, $transfer['from_cage_id'], $transfer['from_cage_assigned_id'], $transfer['from_cagetype'], $this->cage_id )?></td>
		<td><?=makeCageLink ( $this, $transfer['to_cage_id'], $transfer['to_cage_assigned_id'], $transfer['to_cagetype'], $this->cage_id )?></td>
		<td><?=$this->escape ( $transfer['notes'] )?></td>
		<td><?=$this->escape ( $transfer['username'] )?></td>
<td style="text-align:right;"><form method="post" action="<?=$this->url ( array ('controller' => 'transfer', 'action' => 'view', 'id' =>  $transfer['id'] ), null, true ) ?>"
><input type="hidden" name="redirect" value="<?= '/mouse/view/id/' . $this->cage_id ?>" /><input type="hidden" name="edit" value="true" /><?=$this->submitButton('submit_xfer_'.$transfer['id'],
'Edit', array(), array('style' => 'margin-top: -4px; margin-bottom: -2px')) ?></form></td>
	</tr>
<?php endforeach;?>
</table>
<?php endif; ?>
<?php
echo $this->contentPane('tag_pane', null,
    array('href' => $this->url( array('controller' => 'tag', 'action' => 'view', 'table' => Tags::BREEDING_CAGE, 'item' => $this->cage_id,  'format' => 'html' ), null, true ),
    	'parseOnLoad' => 'true',
    	'loadingMessage' => '',
    	'preload' => 'true'),
    array('style' => 'padding:2px;')
    )
?>
<?php
echo $this->contentPane('comment_pane', null,
    array('href' => $this->url( array('controller' => 'comment', 'action' => 'view', 'table' => Comments::BREEDING_CAGE, 'item' => $this->cage_id,  'format' => 'html' ), null, true ),
    	'parseOnLoad' => 'true',
    	'loadingMessage' => '',
    	'preload' => 'true'),
    array('style' => 'padding:2px;')
    )
?>