<?php
Zend_Dojo::enableView($this);
?>
<h2><?=$this->escape($this->title)?></h2>
<?php if (count($this->tags)) : ?>
<?php
$max_count = 2;
foreach ( $this->tags as $tag ){
	if ($tag['count'] > $max_count) {
		$max_count = $tag['count'];
	}
}
?>
<div style="text-align: center;">
<?php foreach ( $this->tags as $tag ) : ?>
<a style="text-decoration: none; background-color:#ffffaa; padding:0 2px 0 2px; font-size: <?=100+round(log(($this->log_base-1)*($tag['count']-1)/($max_count-1)+1, $this->log_base)*100)?>%;" href="<?=$this->url ( array ('controller' => 'tag', 'action' => 'tagged', 'tag' => $tag['tag'] ), null, true )?>"><?=str_replace(' ', '&nbsp;', $this->escape( $tag['tag']) )?></a> &nbsp;
<?php endforeach; ?>
</div>
<?php else : ?>
There are no tags.
<?php endif; ?>