<h2><?=$this->escape($this->title)?></h2>
<div class="noprint">
<form action="<?=$this->url ( array ('action' => 'search' ) )?>"
	method="get"><input type=text size="50" maxlength="500" name="q" /><input
	type="submit" value="Search Weaning Cages" />
	<?php if ($this->canSearch) : ?>
<a href="<?=$this->url ( array ('controller' => 'search', 'action' => 'view', 'subject' => Searches::SUBJECT_WEANING_CAGE ), null, true )?>">advanced</a>
<?php endif; ?>
</form>
</div>
<br />
<p style="color:gray">New weaning cages are created on <a href="<?=$this->url ( array ('controller' => 'litter' ), null, true )?>">litter pages</a>.</p>

<h3>Recently modified weaning cages</h3>
<table class="expand sortable">
	<tr>
		<th>Cage</th>
		<th>Litter</th>
		<th>Sex</th>
		<th>Weaned on</th>
		<th>Modifed on</th>
	</tr>
<?php foreach ( $this->recently_modified_weaning_cages as $cage ) : ?>
<tr>
		<td><a href="<?=$this->url ( array ('controller' => 'weaning-cage', 'action' => 'view', 'id' => $cage['id'] ), null, true )?>"><?=$this->escape ( $cage['assigned_id'] )?></a></td>
		<td><a href="<?=$this->url ( array ('controller' => 'litter', 'action' => 'view', 'id' => $cage['litter_id'] ), null, true )?>"><?=$this->escape ( $cage['litter_assigned_id'] )?></a></td>
		<td><?=$this->escape ( $cage['sex'] )?></td>
		<td><?=$this->escape ( mdb_Globals::formatDateTime($cage['weaned_on']) )?></td>
		<td><?=$this->escape ( mdb_Globals::formatDateTime($cage['lastmodified']) )?></td>
	</tr>
<?php endforeach; ?>
</table>